In [1]:
import pandas as pd

In [4]:
fund = pd.read_csv("c:/Users/Divya/Downloads/MutualFundAnalytics_Project_1/data/raw/fund_master.csv")

In [5]:
fund.head()

,Scheme_Code,Scheme_Name,AMC,Scheme_Type,Scheme_Category,Scheme_NAV_Name,Scheme_Min_Amt,NAV,Latest_NAV_Date,Average_AUM_Cr,AAUM_Quarter,ISIN_Div_Payout/Growth,ISIN_Div_Reinvestment,ISIN_Div_Payout/Growth/Div_Reinvestment,Launch_Date,Closure_Date
0,100033,Aditya Birla Sun Life Large & Mid Cap Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund - R...,5000,930.7900,2026-06-19,4428.2119,January - March 2026,INF209K01165,-,INF209K01165,1995-02-24,1995-02-24
1,100034,Aditya Birla Sun Life Large & Mid Cap Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund -Re...,5000,135.5600,2026-06-19,457.6450,January - March 2026,INF209K01157,INF209K01CE5,INF209K01157INF209K01CE5,1995-02-24,1995-02-24
2,100037,Aditya Birla Sun Life Income Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Regular - ...,5000,12.9582,2026-06-19,11.1344,January - March 2026,INF209K01587,INF209K01CY3,INF209K01587INF209K01CY3,1994-01-01,1994-01-01
3,100038,Aditya Birla Sun Life Income Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Growth - R...,5000,128.6960,2026-06-19,780.1475,January - March 2026,INF209K01579,-,INF209K01579,1994-01-01,1994-01-01
4,100039,Aditya Birla Sun Life Income Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,Birla Income Plus-Institutional (Growth),5000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994-01-01,1994-01-01

In [7]:
fund.columns

Index(['Scheme_Code', 'Scheme_Name', 'AMC', 'Scheme_Type', 'Scheme_Category',
       'Scheme_NAV_Name', 'Scheme_Min_Amt', 'NAV', 'Latest_NAV_Date',
       'Average_AUM_Cr', 'AAUM_Quarter', 'ISIN_Div_Payout/Growth',
       'ISIN_Div_Reinvestment', 'ISIN_Div_Payout/Growth/Div_Reinvestment',
       'Launch_Date', 'Closure_Date'],
      dtype='str')

In [8]:
fund["AMC"].unique()

<StringArray>
[                          'Aditya Birla Sun Life AMC Limited',
                          'DSP Asset Managers Private Limited',
                       'HDFC Asset Management Company Limited',
                                'quant Money Managers Limited',
                       'JM Financial Asset Management Limited',
            'Kotak Mahindra Asset Management Company Limited.',
                    'LIC Mutual Fund Asset Management Limited',
             'Sahara Asset Management Company Private Limited',
           'ICICI Prudential Asset Management Company Limited',
                  'Nippon Life India Asset Management Limited',
                               'Tata Asset Management Limited',
 'Franklin Templeton Asset Management (India) Private Limited',
                     'Taurus Asset Management Company Limited',
              'Canara Robeco Asset Management Company Limited',
                       'Sundaram Asset Management Company Ltd',
                                'SBI Funds Management Limited',
                                    'UTI Asset Mgmt. Co. Ltd.',
   'Baroda BNP Paribas Asset Management India Private Limited',
                  'HSBC Asset Management (India) Private Ltd.',
            'Quantum Asset Management Company Private Limited',
            'Invesco Asset Management (India) Private Limited',
            'Mirae Asset Investment Managers (India) Pvt. Ltd',
                                         'Bandhan AMC Limited',
           'Bank of India Investment Managers Private Limited',
                          'Edelweiss Asset Management Limited',
                              'Axis Asset Management Co. Ltd.',
                                            'Navi AMC Limited',
              'Motilal Oswal Asset Management Company Limited',
                  'PGIM India Asset Management Private Limite',
              'Union Asset Management Company Private Limited',
                              'Groww Asset Management Limited',
                            '360 ONE Asset Management Limited',
                            'PPFAS Asset Management Pvt. Ltd.',
                           'Shriram Asset Management Co. Ltd.',
                             'IIFCL Asset Management Co. Ltd.',
                        'IL&FS Infra Asset Management Limited',
             'Mahindra Manulife Investment Management Pvt Ltd',
                   'WhiteOak Capital Asset Management Limited',
                                'ITI Asset Management Limited',
                      'Trust Asset Management Private Limited',
                         'NJ Asset Management Private Limited',
                      'Samco Asset Management Private Limited',
                      'Bajaj Finserv Asset Management Limited',
           'Helios Capital Asset Management (India) Pvt. Ltd.',
                    'Zerodha Asset Management Private Limited',
                 'Old Bridge Asset Management Private Limited',
                  'Angel One Asset Management Company Limited',
                      'Unifi Asset Management Private Limited',
              'Jio BlackRock Asset Management Private Limited',
                'Capitalmind Asset Management Private Limited',
    'Wealth Company Asset Management Holdings Private Limited',
                                  'Choice AMC Private Limited',
                 'Abakkus Investment Managers Private Limited',
             'AlphaGrep Investment Management Private Limited']
Length: 54, dtype: str

In [9]:
fund.dtypes

Scheme_Code                                  int64
Scheme_Name                                    str
AMC                                            str
Scheme_Type                                    str
Scheme_Category                                str
Scheme_NAV_Name                                str
Scheme_Min_Amt                                 str
NAV                                        float64
Latest_NAV_Date                                str
Average_AUM_Cr                             float64
AAUM_Quarter                                   str
ISIN_Div_Payout/Growth                         str
ISIN_Div_Reinvestment                          str
ISIN_Div_Payout/Growth/Div_Reinvestment        str
Launch_Date                                    str
Closure_Date                                   str
dtype: object

In [10]:
fund.isnull().sum()

Scheme_Code                                    0
Scheme_Name                                    0
AMC                                            0
Scheme_Type                                    0
Scheme_Category                                0
Scheme_NAV_Name                                0
Scheme_Min_Amt                                30
NAV                                         2024
Latest_NAV_Date                             2024
Average_AUM_Cr                              8049
AAUM_Quarter                                8049
ISIN_Div_Payout/Growth                      2024
ISIN_Div_Reinvestment                       2024
ISIN_Div_Payout/Growth/Div_Reinvestment     1387
Launch_Date                                   21
Closure_Date                               12388
dtype: int64

In [11]:
import pandas as pd

fund = pd.read_csv("c:/Users/Divya/Downloads/MutualFundAnalytics_Project_1/data/raw/fund_master.csv")
nav = pd.read_csv("c:/Users/Divya/Downloads/MutualFundAnalytics_Project_1/data/raw/nav_history.csv")

In [12]:
missing_codes = fund[~fund["Scheme_Code"].isin(nav["Scheme_Code"])]

missing_codes

,Scheme_Code,Scheme_Name,AMC,Scheme_Type,Scheme_Category,Scheme_NAV_Name,Scheme_Min_Amt,NAV,Latest_NAV_Date,Average_AUM_Cr,AAUM_Quarter,ISIN_Div_Payout/Growth,ISIN_Div_Reinvestment,ISIN_Div_Payout/Growth/Div_Reinvestment,Launch_Date,Closure_Date
4,100039,Aditya Birla Sun Life Income Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,Birla Income Plus-Institutional (Growth),5000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994-01-01,1994-01-01
5,100040,Aditya Birla Sun Life Income Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,Birla Income Plus-Institutional (Dividend),5000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994-01-01,1994-01-01
13,100050,Aditya Birla Sun Life Liquid Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Liquid Fund,Birla Cash Plus-Birla Cash Plus (Institutional...,Rs. 500/- and in multiples of Re. 1/- thereafter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1997-06-04,1997-06-07
35,100125,HDFC Income Fund,HDFC Asset Management Company Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,HDFC Income Fund-Premium Plan Dividend,REFER SID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-09-11,NaN
36,100126,HDFC Income Fund,HDFC Asset Management Company Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,HDFC Income Fund-Premium Plus Dividend,REFER SID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-09-11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16238,154437,Zerodha Life Cycle Fund 2041,Zerodha Asset Management Private Limited,Open Ended,Hybrid Scheme - Multi Asset Allocation,Zerodha Life Cycle Fund 2041 - Direct - Growth,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-19,NaN
16239,154438,ALPHAGREP MULTI ASSET ALLOCATION FUND,AlphaGrep Investment Management Private Limited,Open Ended,Hybrid Scheme - Multi Asset Allocation,ALPHAGREP MULTI ASSET ALLOCATION FUND-DIRECT-G...,Rs. 500/- and in multiples of Re. 1/- thereafter,NaN,NaN,NaN,NaN,NaN,NaN,INF2VOA01012,2026-07-06,NaN
16240,154440,ALPHAGREP MULTI ASSET ALLOCATION FUND,AlphaGrep Investment Management Private Limited,Open Ended,Hybrid Scheme - Multi Asset Allocation,ALPHAGREP MULTI ASSET ALLOCATION FUND-REGULAR-...,Rs. 500/- and in multiples of Re. 1/- thereafter,NaN,NaN,NaN,NaN,NaN,NaN,INF2VOA01046,2026-07-06,NaN
16241,154442,ALPHAGREP MULTI ASSET ALLOCATION FUND,AlphaGrep Investment Management Private Limited,Open Ended,Hybrid Scheme - Multi Asset Allocation,ALPHAGREP MULTI ASSET ALLOCATION FUND-REGULAR-...,Rs. 500/- and in multiples of Re. 1/- thereafter,NaN,NaN,NaN,NaN,NaN,NaN,INF2VOA01061INF2VOA01053,2026-07-06,NaN
16242,154443,ALPHAGREP MULTI ASSET ALLOCATION FUND,AlphaGrep Investment Management Private Limited,Open Ended,Hybrid Scheme - Multi Asset Allocation,ALPHAGREP MULTI ASSET ALLOCATION FUND-DIRECT-IDCW,Rs. 500/- and in multiples of Re. 1/- thereafter,NaN,NaN,NaN,NaN,NaN,NaN,INF2VOA01038INF2VOA01020,2026-07-06,NaN

In [13]:
missing_codes = fund[fund["Scheme_Code"].isin(nav["Scheme_Code"])]

missing_codes

,Scheme_Code,Scheme_Name,AMC,Scheme_Type,Scheme_Category,Scheme_NAV_Name,Scheme_Min_Amt,NAV,Latest_NAV_Date,Average_AUM_Cr,AAUM_Quarter,ISIN_Div_Payout/Growth,ISIN_Div_Reinvestment,ISIN_Div_Payout/Growth/Div_Reinvestment,Launch_Date,Closure_Date
0,100033,Aditya Birla Sun Life Large & Mid Cap Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund - R...,5000,930.7900,2026-06-19,4428.2119,January - March 2026,INF209K01165,-,INF209K01165,1995-02-24,1995-02-24
1,100034,Aditya Birla Sun Life Large & Mid Cap Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund -Re...,5000,135.5600,2026-06-19,457.6450,January - March 2026,INF209K01157,INF209K01CE5,INF209K01157INF209K01CE5,1995-02-24,1995-02-24
2,100037,Aditya Birla Sun Life Income Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Regular - ...,5000,12.9582,2026-06-19,11.1344,January - March 2026,INF209K01587,INF209K01CY3,INF209K01587INF209K01CY3,1994-01-01,1994-01-01
3,100038,Aditya Birla Sun Life Income Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Growth - R...,5000,128.6960,2026-06-19,780.1475,January - March 2026,INF209K01579,-,INF209K01579,1994-01-01,1994-01-01
6,100041,Aditya Birla Sun Life Liquid Fund,Aditya Birla Sun Life AMC Limited,Open Ended,Debt Scheme - Liquid Fund,Aditya Birla Sun Life Liquid Fund -Institution...,Rs. 500/- and in multiples of Re. 1/- thereafter,108.0230,2026-06-19,0.2125,January - March 2026,-,INF209K01KN9,INF209K01KN9,1997-06-04,1997-06-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16200,154396,Shriram Overnight Fund,Shriram Asset Management Co. Ltd.,Open Ended,Debt Scheme - Overnight Fund,Shriram Overnight Fund- Direct Monthly IDCW,Rs. 500/- and in multiples of Re. 1/- thereafter,1000.8661,2026-06-21,NaN,NaN,INF680P01612,INF680P01638,INF680P01612INF680P01638,2022-08-17,NaN
16202,154398,Shriram Overnight Fund,Shriram Asset Management Co. Ltd.,Open Ended,Debt Scheme - Overnight Fund,Shriram Overnight Fund- Regular Daily IDCW,Rs. 500/- and in multiples of Re. 1/- thereafter,1000.0101,2026-06-21,NaN,NaN,-,INF680P01521,INF680P01521,2022-08-17,NaN
16203,154399,Shriram Overnight Fund,Shriram Asset Management Co. Ltd.,Open Ended,Debt Scheme - Overnight Fund,Shriram Overnight Fund- Regular Growth,Rs. 500/- and in multiples of Re. 1/- thereafter,1254.1346,2026-06-21,NaN,NaN,INF680P01505,-,INF680P01505,2022-08-17,NaN
16206,154402,Shriram Overnight Fund,Shriram Asset Management Co. Ltd.,Open Ended,Debt Scheme - Overnight Fund,Shriram Overnight Fund- Regular Monthly IDCW,Rs. 500/- and in multiples of Re. 1/- thereafter,1000.8964,2026-06-21,NaN,NaN,INF680P01620,INF680P01646,INF680P01620INF680P01646,2022-08-17,NaN
16228,154426,DSP Savings Fund,DSP Asset Managers Private Limited,Open Ended,Debt Scheme - Money Market Fund,DSP Savings Fund - Direct Plan - IDCW Weekly,Rs. 1000/- & any amount thereafter,10.0015,2026-06-19,NaN,NaN,INF740KA1ZD8,INF740KA1ZE6,INF740KA1ZD8INF740KA1ZE6,1999-09-20,1999-09-23